CREATE TABLE markersdata (
  id       int not null auto_increment,
  lng      float(10,6),
  lat       float(10,6),
  stars    integer(11),
  firstname    varchar(60), 
  lastname    varchar(60), 
  gender    varchar(60), 
  bday    date, 
  address varchar(400),
  postcode varchar(100),
  city varchar(100),
  usrtel int,
  qualification varchar(600),
  profile varchar(600),
  subjects    varchar(500),
  level   varchar(500),
  price   varchar(60),
  availability varchar(600),
  img text(500),
  video_link text(500),
  email varchar(100),
  password varchar(100),
  primary key (id)
);